language: python
python:
  - "3.6"
  #- "3.5"

dist: trusty

install:
  - pip install -r requirements.txt

script:
  #- coverage run -m unittest
  - coverage run --omit=*test* -m unittest
  - coverage xml -i
  - sonar-scanner

after_success:
  - codecov
  #- sonar-scanner
  #- coverage xml -i


addons:
 sonarcloud:
   organization: git-confused-team3 # the key of the org you chose at step #3
   token:
     secure: ${newToken}
